defaults:
  - scope:
      path: "collateral"
    values:
      favicon_path: "/collateral/favicons"
      favicon_macos_safari_color: "#8c3f3f"
      favicon_android_theme_color: "#8c3f3f"
      favicon_windows_metro_color: "#8c3f3f"