url: http://c.loc
destination: ./_site
name: christopheraue.net
encoding: UTF-8
permalink: :categories/:title
exclude: [build.sh, deploy.sh, Gemfile, Gemfile.lock]
plugins:
  - jekyll-redirect-from
sass:
  sass_dir: assets/_sass
  style: compressed
  cache_location: assets/_sass/.sass-cache

# Jekyll's site.categories does not return categories without posts. Since
# /collateral doesn't have any it is not included in the list. Hard code it
# here :/
category_list: [design, collateral]

defaults:
  - scope:
      path: ""
    values:
      layout: bare

  - scope:
      path: ""
      type: posts
    values:
      layout: article

  - scope:
      path: "index.html"
    values:
      category: home
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#ffffff"
      favicon_windows_metro_color: "#ffffff"

  - scope:
      path: "design"
    values:
      category: design
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#3f668c"
      favicon_windows_metro_color: "#3f668c"

  - scope:
      path: "collateral"
    values:
      category: collateral
      favicon_macos_safari_color: "#8c3f3f"
      favicon_android_theme_color: "#8c3f3f"
      favicon_windows_metro_color: "#8c3f3f"
