url: http://c.loc
destination: ./_site
name: christopheraue.net
permalink: :categories/:title
plugins:
  - jekyll-redirect-from
  - jekyll-components
  - jekyll-components-base_components
  - jekyll-category_tree

google_fonts: Work+Sans:300,500|Source+Code+Pro:300,500,900|Open+Sans+Condensed:700

defaults:
  - scope:
      path: ""
    values:
      render_inside: Page
      robots: index, follow
      lang: en
      author: Christopher Aue
      hide_header: false
      hide_footer: false
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#ffffff"
      favicon_windows_metro_color: "#ffffff"
