url: http://c.loc
destination: ./_site
name: christopheraue.net
description: A place for Christopher Aue to write about stuff.
encoding: UTF-8
permalink: :categories/:title
exclude: [test, sass, build.sh, deploy.sh, set_development_env.sh, set_production_env.sh, videos, Gemfile, Gemfile.lock]
plugins:
  - jekyll-redirect-from

# Jekyll's site.categories does not return categories without posts. Since
# /collateral doesn't have any it is not included in the list. Hard code it
# here :/
category_list: [technical, collateral]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "with_header"

  - scope:
      path: "technical"
    values:
      categories: "technical"
