url: http://c.loc
destination: ./_site
name: christopheraue.net
author: Christopher Aue
encoding: UTF-8
permalink: :categories
exclude: [build.sh, deploy.sh, Gemfile, Gemfile.lock]
plugins:
  - jekyll-redirect-from
  - jekyll-components
  - jekyll-components-base_components
  - jekyll-category_tree
sass:
  load_paths: [/]
  cache_location: _build/.sass-cache

defaults:
  - scope:
      path: ""
    values:
      render_inside: Root
      robots: index, follow
      lang: en

  - scope:
      path: "index.html"
    values:
      category: home
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#ffffff"
      favicon_windows_metro_color: "#ffffff"

  - scope:
      path: "design"
    values:
      category: design
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#3f668c"
      favicon_windows_metro_color: "#3f668c"

  - scope:
      path: "design"
      type: posts
    values:
      render_inside: design-Article

  - scope:
      path: "collateral"
    values:
      category: collateral
      favicon_macos_safari_color: "#8c3f3f"
      favicon_android_theme_color: "#8c3f3f"
      favicon_windows_metro_color: "#8c3f3f"
