url: http://c.loc
destination: ./_site
name: christopheraue.net
encoding: UTF-8
permalink: :categories/:title
exclude: [build.sh, deploy.sh, Gemfile, Gemfile.lock]
plugins:
  - jekyll-redirect-from

# Jekyll's site.categories does not return categories without posts. Since
# /collateral doesn't have any it is not included in the list. Hard code it
# here :/
category_list: [design, collateral]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "with_header"

  - scope:
      path: "home"
    values:
      category: "home"
      favicon_background_color: #3f668c
      favicon_android_theme_color: #ffffff

  - scope:
      path: "design"
    values:
      category: "design"
      favicon_background_color: #3f668c
      favicon_android_theme_color: #3f668c

  - scope:
      path: "collateral"
    values:
      category: "collateral"
      favicon_background_color: #8c3f3f
      favicon_android_theme_color: #8c3f3f
