name: christopheraue.net
url: https://c.loc
destination: ./_site

plugins:
  - jekyll-nginx_redirects
  - jekyll-components-base_components
  - jekyll-category_tree

defaults:
  - scope:
      path: ""
    values:
      wrap_body_in: Page
      robots: index, follow
      lang: en
      author: Christopher Aue
      hide_header: false
      hide_footer: false
      referrer: unsafe-url
      favicon_path: "/design/favicons"
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#3f668c"
      favicon_windows_metro_color: "#3f668c"
