url: http://c.loc
destination: ./_site
name: christopheraue.net
encoding: UTF-8
permalink: :categories/:title
exclude: [build.sh, deploy.sh, Gemfile, Gemfile.lock]
plugins:
  - jekyll-redirect-from
  - jekyll-components
component_repositories:
  '': jekyll-components-base_components
sass:
  load_paths: [_components/_base/_sass]
  cache_location: _build/.sass-cache

# Jekyll's site.categories does not return categories without posts. Since
# /collateral doesn't have any it is not included in the list. Hard code it
# here :/
category_list: [design, collateral]

defaults:
  - scope:
      path: ""
    values:
      render_inside: root-Root

  - scope:
      path: "index.html"
    values:
      category: home
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#ffffff"
      favicon_windows_metro_color: "#ffffff"

  - scope:
      path: "design"
    values:
      category: design
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#3f668c"
      favicon_windows_metro_color: "#3f668c"

  - scope:
      path: "design"
      type: posts
    values:
      render_inside: design-Article

  - scope:
      path: "collateral"
    values:
      category: collateral
      favicon_macos_safari_color: "#8c3f3f"
      favicon_android_theme_color: "#8c3f3f"
      favicon_windows_metro_color: "#8c3f3f"
