url: http://ca.local
destination: ./_site
name: Christopher Aue
description: This is a place where I gather resources and write about *Web Technology*, *Product Development* and *Self-Improvement*.
default_background: blur_lightbeam.jpg
encoding: UTF-8
pygments: false
permalink: :year/:month/:day/:title/
exclude: [test, sass, build.sh, deploy.sh, set_development_env.sh, set_production_env.sh]