defaults:
  - scope:
      path: "design"
    values:
      include_in_body: design-Page
      favicon_path: "/design/favicons"
      favicon_macos_safari_color: "#3f668c"
      favicon_android_theme_color: "#3f668c"
      favicon_windows_metro_color: "#3f668c"

  - scope:
      path: "design"
      type: posts
    values:
      include_in_body: design-ArticlePage