[
   {
      "created_at":"Thu Jan 09 16:44:09 +0000 2014",
      "id":421321506891636736,
      "id_str":"421321506891636736",
      "text":"Placeit - Generate Product Screenshots in Realistic Environments https:\/\/t.co\/EOtwdoiWsy #placeit via @placeitapp",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":0,
      "entities":{
         "hashtags":[
            {
               "text":"placeit",
               "indices":[
                  89,
                  97
               ]
            }
         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"https:\/\/t.co\/EOtwdoiWsy",
               "expanded_url":"https:\/\/placeit.net",
               "display_url":"placeit.net",
               "indices":[
                  65,
                  88
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"placeitapp",
               "name":"Placeit",
               "id":2149691558,
               "id_str":"2149691558",
               "indices":[
                  102,
                  113
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Wed Jan 08 20:55:27 +0000 2014",
      "id":421022359697379328,
      "id_str":"421022359697379328",
      "text":"@rrhoover You're welcome. I like your articles!",
      "source":"web",
      "truncated":false,
      "in_reply_to_status_id":421020778390634496,
      "in_reply_to_status_id_str":"421020778390634496",
      "in_reply_to_user_id":14417215,
      "in_reply_to_user_id_str":"14417215",
      "in_reply_to_screen_name":"rrhoover",
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":1,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[

         ],
         "user_mentions":[
            {
               "screen_name":"rrhoover",
               "name":"Ryan Hoover",
               "id":14417215,
               "id_str":"14417215",
               "indices":[
                  0,
                  9
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "lang":"en"
   },
   {
      "created_at":"Wed Jan 08 20:44:53 +0000 2014",
      "id":421019700294725632,
      "id_str":"421019700294725632",
      "text":"How We Got Our First 2,000 Users Doing Things That Don't Scale | Ryan Hoover http:\/\/t.co\/k1skE5TrpI via @rrhoover",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":1,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/k1skE5TrpI",
               "expanded_url":"http:\/\/ryanhoover.me\/post\/72663537463\/how-we-got-our-first-2-000-users-doing-things-that",
               "display_url":"ryanhoover.me\/post\/726635374\u2026",
               "indices":[
                  77,
                  99
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"rrhoover",
               "name":"Ryan Hoover",
               "id":14417215,
               "id_str":"14417215",
               "indices":[
                  104,
                  113
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Sun Jan 05 11:55:49 +0000 2014",
      "id":419799393953656832,
      "id_str":"419799393953656832",
      "text":"RT @TheNextWeb: POPULAR RIGHT NOW:\n20 of the best productivity apps of 2013 \u27a4 http:\/\/t.co\/oGiAzaow6h http:\/\/t.co\/sdcZd9cav8",
      "source":"web",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweeted_status":{
         "created_at":"Sat Jan 04 00:40:42 +0000 2014",
         "id":419267104664080384,
         "id_str":"419267104664080384",
         "text":"POPULAR RIGHT NOW:\n20 of the best productivity apps of 2013 \u27a4 http:\/\/t.co\/oGiAzaow6h http:\/\/t.co\/sdcZd9cav8",
         "source":"\u003ca href=\"https:\/\/about.twitter.com\/products\/tweetdeck\" rel=\"nofollow\"\u003eTweetDeck\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":10876852,
            "id_str":"10876852",
            "name":"The Next Web",
            "screen_name":"TheNextWeb",
            "location":"The Interwebs.",
            "description":"International news on technology, business and culture. Follow specific channels in our Twitter lists.  Find us on Facebook:  http:\/\/t.co\/pcgAUcQggv",
            "url":"http:\/\/t.co\/BV4ajjxry7",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/BV4ajjxry7",
                        "expanded_url":"http:\/\/thenextweb.com",
                        "display_url":"thenextweb.com",
                        "indices":[
                           0,
                           22
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/pcgAUcQggv",
                        "expanded_url":"http:\/\/www.facebook.com\/thenextweb",
                        "display_url":"facebook.com\/thenextweb",
                        "indices":[
                           126,
                           148
                        ]
                     }
                  ]
               }
            },
            "protected":false,
            "followers_count":1026755,
            "friends_count":1092,
            "listed_count":23636,
            "created_at":"Wed Dec 05 17:26:15 +0000 2007",
            "favourites_count":296,
            "utc_offset":3600,
            "time_zone":"Amsterdam",
            "geo_enabled":false,
            "verified":true,
            "statuses_count":58993,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "is_translation_enabled":false,
            "profile_background_color":"000000",
            "profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/378800000164731038\/_3evIEjW.jpeg",
            "profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/378800000164731038\/_3evIEjW.jpeg",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000147133877\/895fa7d3daeed8d32b7c089d9b3e976e_normal.png",
            "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000147133877\/895fa7d3daeed8d32b7c089d9b3e976e_normal.png",
            "profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/10876852\/1385744395",
            "profile_link_color":"FF3C1F",
            "profile_sidebar_border_color":"FFFFFF",
            "profile_sidebar_fill_color":"F3F3F3",
            "profile_text_color":"333333",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":true,
            "follow_request_sent":false,
            "notifications":false
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":26,
         "favorite_count":54,
         "entities":{
            "hashtags":[

            ],
            "symbols":[

            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/oGiAzaow6h",
                  "expanded_url":"http:\/\/tnw.co\/1khHlfC",
                  "display_url":"tnw.co\/1khHlfC",
                  "indices":[
                     62,
                     84
                  ]
               }
            ],
            "user_mentions":[

            ],
            "media":[
               {
                  "id":419267104408207360,
                  "id_str":"419267104408207360",
                  "indices":[
                     85,
                     107
                  ],
                  "media_url":"http:\/\/pbs.twimg.com\/media\/BdGJNchCAAAlFkP.png",
                  "media_url_https":"https:\/\/pbs.twimg.com\/media\/BdGJNchCAAAlFkP.png",
                  "url":"http:\/\/t.co\/sdcZd9cav8",
                  "display_url":"pic.twitter.com\/sdcZd9cav8",
                  "expanded_url":"http:\/\/twitter.com\/TheNextWeb\/status\/419267104664080384\/photo\/1",
                  "type":"photo",
                  "sizes":{
                     "large":{
                        "w":1024,
                        "h":534,
                        "resize":"fit"
                     },
                     "thumb":{
                        "w":150,
                        "h":150,
                        "resize":"crop"
                     },
                     "medium":{
                        "w":600,
                        "h":313,
                        "resize":"fit"
                     },
                     "small":{
                        "w":340,
                        "h":177,
                        "resize":"fit"
                     }
                  }
               }
            ]
         },
         "favorited":false,
         "retweeted":true,
         "possibly_sensitive":false,
         "lang":"en"
      },
      "retweet_count":26,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/oGiAzaow6h",
               "expanded_url":"http:\/\/tnw.co\/1khHlfC",
               "display_url":"tnw.co\/1khHlfC",
               "indices":[
                  78,
                  100
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"TheNextWeb",
               "name":"The Next Web",
               "id":10876852,
               "id_str":"10876852",
               "indices":[
                  3,
                  14
               ]
            }
         ],
         "media":[
            {
               "id":419267104408207360,
               "id_str":"419267104408207360",
               "indices":[
                  101,
                  123
               ],
               "media_url":"http:\/\/pbs.twimg.com\/media\/BdGJNchCAAAlFkP.png",
               "media_url_https":"https:\/\/pbs.twimg.com\/media\/BdGJNchCAAAlFkP.png",
               "url":"http:\/\/t.co\/sdcZd9cav8",
               "display_url":"pic.twitter.com\/sdcZd9cav8",
               "expanded_url":"http:\/\/twitter.com\/TheNextWeb\/status\/419267104664080384\/photo\/1",
               "type":"photo",
               "sizes":{
                  "large":{
                     "w":1024,
                     "h":534,
                     "resize":"fit"
                  },
                  "thumb":{
                     "w":150,
                     "h":150,
                     "resize":"crop"
                  },
                  "medium":{
                     "w":600,
                     "h":313,
                     "resize":"fit"
                  },
                  "small":{
                     "w":340,
                     "h":177,
                     "resize":"fit"
                  }
               }
            }
         ]
      },
      "favorited":false,
      "retweeted":true,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Sun Jan 05 11:00:59 +0000 2014",
      "id":419785592894148608,
      "id_str":"419785592894148608",
      "text":"RT @msuster: Just love reading @sgblank posts \u201dIf things seem under control u are not going fast enough\u201d Mario Andretti\nhttp:\/\/t.co\/3hATWzE\u2026",
      "source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweeted_status":{
         "created_at":"Fri Jan 03 22:56:32 +0000 2014",
         "id":419240892562567168,
         "id_str":"419240892562567168",
         "text":"Just love reading @sgblank posts \u201dIf things seem under control u are not going fast enough\u201d Mario Andretti\nhttp:\/\/t.co\/3hATWzEex6",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":418939567538855936,
         "in_reply_to_status_id_str":"418939567538855936",
         "in_reply_to_user_id":22747624,
         "in_reply_to_user_id_str":"22747624",
         "in_reply_to_screen_name":"sgblank",
         "user":{
            "id":5520332,
            "id_str":"5520332",
            "name":"Mark Suster",
            "screen_name":"msuster",
            "location":"Los Angeles",
            "description":"2x entrepreneur. Sold both companies (last to http:\/\/t.co\/Q4dBn3Ye). Turned VC looking to invest in passionate entrepreneurs",
            "url":"http:\/\/t.co\/rgbLLec5NZ",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/rgbLLec5NZ",
                        "expanded_url":"http:\/\/bothsid.es",
                        "display_url":"bothsid.es",
                        "indices":[
                           0,
                           22
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/Q4dBn3Ye",
                        "expanded_url":"http:\/\/salesforce.com",
                        "display_url":"salesforce.com",
                        "indices":[
                           46,
                           66
                        ]
                     }
                  ]
               }
            },
            "protected":false,
            "followers_count":144680,
            "friends_count":788,
            "listed_count":6505,
            "created_at":"Thu Apr 26 06:43:28 +0000 2007",
            "favourites_count":2872,
            "utc_offset":-28800,
            "time_zone":"Pacific Time (US & Canada)",
            "geo_enabled":true,
            "verified":true,
            "statuses_count":20993,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "is_translation_enabled":false,
            "profile_background_color":"9AE4E8",
            "profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/4977283\/s_sunset23.jpg",
            "profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/4977283\/s_sunset23.jpg",
            "profile_background_tile":true,
            "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/3099951524\/3fc26aac6ff9a772f29bc525ee902390_normal.png",
            "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/3099951524\/3fc26aac6ff9a772f29bc525ee902390_normal.png",
            "profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/5520332\/1358017488",
            "profile_link_color":"0000FF",
            "profile_sidebar_border_color":"87BC44",
            "profile_sidebar_fill_color":"E0FF92",
            "profile_text_color":"000000",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":true,
            "follow_request_sent":false,
            "notifications":false
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":28,
         "favorite_count":25,
         "entities":{
            "hashtags":[

            ],
            "symbols":[

            ],
            "urls":[
               {
                  "url":"http:\/\/t.co\/3hATWzEex6",
                  "expanded_url":"http:\/\/steveblank.wordpress.com\/2009\/04\/10\/good-enough-decision-making\/?preview=true&preview_id=782&preview_nonce=7a9bf9802c",
                  "display_url":"steveblank.wordpress.com\/2009\/04\/10\/goo\u2026",
                  "indices":[
                     107,
                     129
                  ]
               }
            ],
            "user_mentions":[
               {
                  "screen_name":"sgblank",
                  "name":"steve blank",
                  "id":22747624,
                  "id_str":"22747624",
                  "indices":[
                     18,
                     26
                  ]
               }
            ]
         },
         "favorited":false,
         "retweeted":true,
         "possibly_sensitive":false,
         "lang":"en"
      },
      "retweet_count":28,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/3hATWzEex6",
               "expanded_url":"http:\/\/steveblank.wordpress.com\/2009\/04\/10\/good-enough-decision-making\/?preview=true&preview_id=782&preview_nonce=7a9bf9802c",
               "display_url":"steveblank.wordpress.com\/2009\/04\/10\/goo\u2026",
               "indices":[
                  139,
                  140
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"msuster",
               "name":"Mark Suster",
               "id":5520332,
               "id_str":"5520332",
               "indices":[
                  3,
                  11
               ]
            },
            {
               "screen_name":"sgblank",
               "name":"steve blank",
               "id":22747624,
               "id_str":"22747624",
               "indices":[
                  31,
                  39
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":true,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Fri Jan 03 11:50:02 +0000 2014",
      "id":419073163075411968,
      "id_str":"419073163075411968",
      "text":"\u201cHow A Football Coach Taught Me To Product Manage Like a Boss\u201d by @biggiesu https:\/\/t.co\/iisBDBqku0",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"https:\/\/t.co\/iisBDBqku0",
               "expanded_url":"https:\/\/medium.com\/p\/926ab5c39156",
               "display_url":"medium.com\/p\/926ab5c39156",
               "indices":[
                  76,
                  99
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"biggiesu",
               "name":"Mike Su",
               "id":14534212,
               "id_str":"14534212",
               "indices":[
                  66,
                  75
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Fri Jan 03 11:35:38 +0000 2014",
      "id":419069537300926466,
      "id_str":"419069537300926466",
      "text":"Product managers: Vision, instinct &amp; obsession. (And the rest). - http:\/\/t.co\/EsD0tryOMv",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/EsD0tryOMv",
               "expanded_url":"http:\/\/tmblr.co\/ZP7Vhx1311vVz",
               "display_url":"tmblr.co\/ZP7Vhx1311vVz",
               "indices":[
                  70,
                  92
               ]
            }
         ],
         "user_mentions":[

         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Thu Jan 02 19:41:29 +0000 2014",
      "id":418829417884831745,
      "id_str":"418829417884831745",
      "text":"Can space really be negative? http:\/\/t.co\/FDZcuu3ygW via @designerdepot",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/FDZcuu3ygW",
               "expanded_url":"http:\/\/www.webdesignerdepot.com\/2013\/10\/can-space-really-be-negative\/",
               "display_url":"webdesignerdepot.com\/2013\/10\/can-sp\u2026",
               "indices":[
                  30,
                  52
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"DesignerDepot",
               "name":"Webdesigner Depot",
               "id":17636405,
               "id_str":"17636405",
               "indices":[
                  57,
                  71
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   },
   {
      "created_at":"Thu Jan 02 11:36:02 +0000 2014",
      "id":418707250648084482,
      "id_str":"418707250648084482",
      "text":"RT @lukew: What's better than discussing? Designing. What's better than designing? Coding. What's better than coding? Shipping.",
      "source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweeted_status":{
         "created_at":"Thu Nov 28 01:13:18 +0000 2013",
         "id":405866958165258240,
         "id_str":"405866958165258240",
         "text":"What's better than discussing? Designing. What's better than designing? Coding. What's better than coding? Shipping.",
         "source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
         "truncated":false,
         "in_reply_to_status_id":null,
         "in_reply_to_status_id_str":null,
         "in_reply_to_user_id":null,
         "in_reply_to_user_id_str":null,
         "in_reply_to_screen_name":null,
         "user":{
            "id":13889622,
            "id_str":"13889622",
            "name":"Luke Wroblewski",
            "screen_name":"lukew",
            "location":"Silicon Valley + the Web",
            "description":"Digital product design & strategy guy in Silicon Valley. Known for Mobile First, Web Form Design, Polar, Bagcheck, ...",
            "url":"http:\/\/t.co\/eTQHZeellQ",
            "entities":{
               "url":{
                  "urls":[
                     {
                        "url":"http:\/\/t.co\/eTQHZeellQ",
                        "expanded_url":"http:\/\/www.lukew.com",
                        "display_url":"lukew.com",
                        "indices":[
                           0,
                           22
                        ]
                     }
                  ]
               },
               "description":{
                  "urls":[

                  ]
               }
            },
            "protected":false,
            "followers_count":79261,
            "friends_count":97,
            "listed_count":5813,
            "created_at":"Sun Feb 24 04:01:42 +0000 2008",
            "favourites_count":2318,
            "utc_offset":-28800,
            "time_zone":"Pacific Time (US & Canada)",
            "geo_enabled":true,
            "verified":false,
            "statuses_count":13094,
            "lang":"en",
            "contributors_enabled":false,
            "is_translator":false,
            "is_translation_enabled":false,
            "profile_background_color":"FFFFFF",
            "profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/333653482\/Screen_shot_2011-09-20_at_10.32.22_AM.png",
            "profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/333653482\/Screen_shot_2011-09-20_at_10.32.22_AM.png",
            "profile_background_tile":false,
            "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/2924627654\/c28337b0191a03064ba289db29564dc8_normal.png",
            "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/2924627654\/c28337b0191a03064ba289db29564dc8_normal.png",
            "profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/13889622\/1348540123",
            "profile_link_color":"449400",
            "profile_sidebar_border_color":"88D822",
            "profile_sidebar_fill_color":"E3F8AF",
            "profile_text_color":"484242",
            "profile_use_background_image":true,
            "default_profile":false,
            "default_profile_image":false,
            "following":false,
            "follow_request_sent":false,
            "notifications":false
         },
         "geo":null,
         "coordinates":null,
         "place":null,
         "contributors":null,
         "retweet_count":255,
         "favorite_count":187,
         "entities":{
            "hashtags":[

            ],
            "symbols":[

            ],
            "urls":[

            ],
            "user_mentions":[

            ]
         },
         "favorited":true,
         "retweeted":true,
         "lang":"en"
      },
      "retweet_count":255,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[

         ],
         "user_mentions":[
            {
               "screen_name":"lukew",
               "name":"Luke Wroblewski",
               "id":13889622,
               "id_str":"13889622",
               "indices":[
                  3,
                  9
               ]
            }
         ]
      },
      "favorited":true,
      "retweeted":true,
      "lang":"en"
   },
   {
      "created_at":"Wed Jan 01 12:37:32 +0000 2014",
      "id":418360338359148544,
      "id_str":"418360338359148544",
      "text":"Learn to think big http:\/\/t.co\/jqNHlc89KI via @yegg",
      "source":"\u003ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003eTweet Button\u003c\/a\u003e",
      "truncated":false,
      "in_reply_to_status_id":null,
      "in_reply_to_status_id_str":null,
      "in_reply_to_user_id":null,
      "in_reply_to_user_id_str":null,
      "in_reply_to_screen_name":null,
      "user":{
         "id":253575497,
         "id_str":"253575497",
         "name":"Christopher Aue",
         "screen_name":"christopheraue",
         "location":"Germany",
         "description":"",
         "url":"http:\/\/t.co\/YoaOPCJ1qc",
         "entities":{
            "url":{
               "urls":[
                  {
                     "url":"http:\/\/t.co\/YoaOPCJ1qc",
                     "expanded_url":"http:\/\/christopheraue.net",
                     "display_url":"christopheraue.net",
                     "indices":[
                        0,
                        22
                     ]
                  }
               ]
            },
            "description":{
               "urls":[

               ]
            }
         },
         "protected":false,
         "followers_count":7,
         "friends_count":14,
         "listed_count":0,
         "created_at":"Thu Feb 17 14:41:06 +0000 2011",
         "favourites_count":1,
         "utc_offset":3600,
         "time_zone":"Amsterdam",
         "geo_enabled":false,
         "verified":false,
         "statuses_count":34,
         "lang":"en",
         "contributors_enabled":false,
         "is_translator":false,
         "is_translation_enabled":false,
         "profile_background_color":"C0DEED",
         "profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
         "profile_background_tile":false,
         "profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/378800000847541191\/c52da5baadf1eeb7e2e06ad803936d20_normal.png",
         "profile_link_color":"0084B4",
         "profile_sidebar_border_color":"C0DEED",
         "profile_sidebar_fill_color":"DDEEF6",
         "profile_text_color":"333333",
         "profile_use_background_image":true,
         "default_profile":true,
         "default_profile_image":false,
         "following":false,
         "follow_request_sent":false,
         "notifications":false
      },
      "geo":null,
      "coordinates":null,
      "place":null,
      "contributors":null,
      "retweet_count":0,
      "favorite_count":0,
      "entities":{
         "hashtags":[

         ],
         "symbols":[

         ],
         "urls":[
            {
               "url":"http:\/\/t.co\/jqNHlc89KI",
               "expanded_url":"http:\/\/www.gabrielweinberg.com\/blog\/2013\/12\/learn-to-think-big.html",
               "display_url":"gabrielweinberg.com\/blog\/2013\/12\/l\u2026",
               "indices":[
                  19,
                  41
               ]
            }
         ],
         "user_mentions":[
            {
               "screen_name":"yegg",
               "name":"Gabriel Weinberg",
               "id":14492722,
               "id_str":"14492722",
               "indices":[
                  46,
                  51
               ]
            }
         ]
      },
      "favorited":false,
      "retweeted":false,
      "possibly_sensitive":false,
      "lang":"en"
   }
]